// query users logs where id === 1
const userLogs = {
  user: {
    id: 1,
    email: "example@dummy.com",
    name: "Bob Bobberson",
    logs: [
      {
        id: 1,
        public: true,
        date: new Date().toISOString(),
        dive_site: "Bobo's Lagoon",
        city: "Panama City",
        country: "United States",
        visibility: "10 feet",
        air_temp: "85 degrees fahrenheit",
        water_temp: "75 degrees fahrenheit",
        weight: "12 pounds",
        hood: false,
        gloves: false,
        wet_suit: true,
        waves: true,
        current: false,
        controlled_env: true,
        salt_water: true,
        boat: false,
        max_depth: "50 feet",
        time_in: new Date().toISOString(),
        time_out: new Date().toISOString(),
        rnt: 20,
        abt: 15,
        tbt: 35,
        start_pressure: "5 psi",
        end_pressure: "10 psi",
        notes: "I saw a sea turtle and a jellyfish!",
        dive_center: "Big Island Divers",
        dive_instructor: "Frank",
        instructor_cert: "123456",
        photos: [
          {
            id: 1,
            url: "https://images.unsplash.com/photo-1589634749362-a8ef3056cbe9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80",
            id_log: 1,
          },
          {
            id: 2,
            url: "https://images.unsplash.com/photo-1495012379376-194a416fcc5f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1934&q=80",
            id_log: 1,
          },
        ],
        tags: [
          "Bobo's Lagoon",
          "Panama City",
          "United States",
          "#wow",
          "#ballin",
          "sea turtle",
          "jellyfish",
        ],
      },
      {
        id: 2,
        public: false,
        id_user: 1,
        date: new Date().toISOString(),
        dive_site: "Bobo's Palace",
        city: "Galveston",
        country: "United States",
        visibility: "8 feet",
        air_temp: "90 degress F",
        water_temp: "82 degrees F",
        weight: "14 pounds",
        hood: true,
        gloves: true,
        wet_suit: false,
        waves: false,
        current: true,
        controlled_env: false,
        salt_water: true,
        boat: true,
        max_depth: "75 feet",
        time_in: new Date().toISOString(),
        time_out: new Date().toISOString(),
        rnt: 15,
        abt: 10,
        tbt: 25,
        start_pressure: "6 psi",
        end_pressure: "12 psi",
        notes: "I saw a sea turtle and a sea star!",
        dive_center: "Big Island Divers",
        dive_instructor: "Frank",
        instructor_cert: "123456",
        photos: [
          {
            id: 3,
            url: "https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1400&q=80",
            id_log: 1,
          },
          {
            id: 4,
            url: "https://images.unsplash.com/photo-1610981263015-ef95481e9ffb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=675&q=80",
            id_log: 1,
          },
        ],
        tags: [
          "Bobo's Palace",
          "Galveston",
          "United States",
          "sea turtle",
          "sea star",
          "#scubaislife",
        ],
      },
    ],
  },
};

// query for all logs to go in the feed ->
const allLogs = {
  logs: [
    {
      id: 1,
      name: "Bob Bobberson",
      public: true,
      date: new Date().toISOString(),
      dive_site: "Bobo's Lagoon",
      city: "Panama City",
      country: "United States",
      photos: [
        {
          id: 1,
          url: "https://images.unsplash.com/photo-1589634749362-a8ef3056cbe9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2775&q=80",
          id_log: 1,
        },
        {
          id: 2,
          url: "https://images.unsplash.com/photo-1495012379376-194a416fcc5f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=734&q=80",
          id_log: 1,
        },
      ],
      tags: [
        "Bobo's Lagoon",
        "Panama City",
        "United States",
        "#wow",
        "#ballin",
        "sea turtle",
        "jellyfish",
      ],
    },
    {
      id: 2,
      name: "Jeff Jeffery",
      public: true,
      date: new Date().toISOString(),
      dive_site: "Jeff's Lagoon",
      city: "Janama City",
      country: "United States",
      photos: [
        {
          id: 1,
          url: "https://lh3.googleusercontent.com/pw/ACtC-3dd06mDTFNxgENz4V7qDO85hADkg6o-0IrbumH5iRrrfHHjaUtKVAieLvv0wdnDPG_dvpxjSuIoQaTJ--dX809aFKFvbK9-7nOIShY1sUkHRAItbPXxqiz-K6S2JM6K9Pu5mSPpv_KGzBJ7oxlTrkrV=w1368-h913-no?authuser=1",
          id_log: 1,
        },
        {
          id: 2,
          url: "https://lh3.googleusercontent.com/pw/ACtC-3e_lmDcFzx_r9tha_VWCatqYO48HzGfEKDBCI2CwAHr8vY0v74AKFOF0y5pPz3DQMuNtGUX9xxYp6PDKxhSkEh_8_dTGM3x-l0YprkgZvlTzOqcNHe-DLckryGSZpTYC9LW4S4w-fH89qMfDx1gCZHa=w1368-h912-no?authuser=1",
          id_log: 1,
        },
        {
          id: 3,
          url: "https://lh3.googleusercontent.com/pw/ACtC-3eeFTy8cK-0E5b8_G8zydFGCjH6v-dw-7itCjF2sfNErtXdXjNmiyqzCHk3ekFsuEnUYHiL2fAZqfq5ztee7xKoTktWnVS_oD9U7qt2ghydyKesY4RbktntRrPU5qYjJDTlG4u07xxRfTL0Ly1-TL3s=w1279-h912-no?authuser=1",
          id_log: 1,
        },
        {
          id: 4,
          url: "https://lh3.googleusercontent.com/pw/ACtC-3f8EPbpYQUGh8oBN5SKmCRv3xoZlJ4DE_sI7gsbNlVNZe7dwOQHe1n0c-KmYPFpJ1gxa8SdzyJdAr8i-pWV3xXyGR7Z6UlNG0uibPka0uXB0khUEO8Lba1pYRx3KHO-lvOUF_RAS8vtHiQpDK5s7jzg=w1368-h912-no?authuser=1",
          id_log: 1,
        },
        {
          id: 5,
          url: "https://lh3.googleusercontent.com/pw/ACtC-3fiP8vZQcSQ5JKfv41Y2DkPeJC5FdWZ0Eqcszzbdw1WA_1yr1TuuZ_kaZXoTR3KwsfkfvGXHNCkpjpR1cHYIHOIKX5keYz-qTZM5bU7nEsifDl0i78KEiGzZG1V5ZCqmSJG6jDeM8_Ny1GWmIEFu0mL=w1368-h912-no?authuser=1",
          id_log: 1,
        },
        {
          id: 6,
          url: "https://lh3.googleusercontent.com/pw/ACtC-3fjysBQyBh5P8j_um_xQgdR9fYaP24qiSjAaZCeFjG0ahR_zUW7_6s33IOBHz5M12OqNS6-GQH4GkF7y0CEoqel29RIr5Fo2MPKbLRYDTtIrTd7NQt2LFmYWRnCrpyq4Ix-unC1UxdqxCo_2weteq0e=w1368-h912-no?authuser=1",
          id_log: 1,
        },
      ],
      tags: [
        "Jeff's Lagoon",
        "Janama City",
        "United States",
        "Shark",
        "sea Turtle",
        "star fish",
      ],
    },
    {
      id: 3,
      name: "Job Cobberson",
      public: true,
      date: new Date().toISOString(),
      dive_site: "Jbo's Lagoon",
      city: "Jama City",
      country: "J States",
      photos: [
        {
          id: 1,
          url: "https://lh3.googleusercontent.com/pw/ACtC-3fjysBQyBh5P8j_um_xQgdR9fYaP24qiSjAaZCeFjG0ahR_zUW7_6s33IOBHz5M12OqNS6-GQH4GkF7y0CEoqel29RIr5Fo2MPKbLRYDTtIrTd7NQt2LFmYWRnCrpyq4Ix-unC1UxdqxCo_2weteq0e=w1368-h912-no?authuser=1",
          id_log: 1,
        },
      ],
      tags: ["Jbo's Lagoon", "Jama City", "J States", "#wow", "#ballin"],
    },
  ],
};
const userTags = {
  id: 1,
  email: "example@dummy.com",
  name: "Bob Bobberson",
  tags: [
    "Bobo's Lagoon",
    "Panama City",
    "United States",
    "#wow",
    "#ballin",
    "sea turtle",
    "jellyfish",
    "Bobo's Palace",
    "Galveston",
    "sea star",
    "#scubaislife",
  ],
};

const tags = [
  "Bobo's Lagoon",
  "Panama City",
  "United States",
  "#wow",
  "#ballin",
  "sea turtle",
  "jellyfish",
  "Bobo's Palace",
  "Galveston",
  "sea star",
  "#scubaislife",
  "Shark",
  "star fish",
  "Jbo's Lagoon",
  "Jama City",
  "J States",
];

export default {
  userLogs: userLogs,
  allLogs: allLogs,
  userTags: userTags,
  tags: tags,
};
